# Copyright 2024 The Kubernetes Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: test-publish-release-action

on:
  pull_request:
    branches:
      - 'main'
  push:
    branches:
      - 'main'

permissions: {}

jobs:
  changes:
    runs-on: ubuntu-latest

    permissions:
      pull-requests: read
      contents: read

    outputs:
      pr: ${{ steps.filter.outputs.pr }}

    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

      - uses: dorny/paths-filter@de90cc6fb38fc0963ad72b210f1f284cd68cea36 # v3.0.2
        id: filter
        with:
          filters: |
            pr:
              - 'publish-release/**'
              - '.github/workflows/test-publish-release.yaml'

  test_publish_release_action:
    if: ${{ needs.changes.outputs.pr == 'true' }}
    needs:
      - changes
    strategy:
      matrix:
        os:
          - macos-latest
          - ubuntu-latest

    runs-on: ${{ matrix.os }}

    permissions:
      contents: read

    name: Install publish-release and test presence in path
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          persist-credentials: false

      - name: Install publish-release
        uses: ./publish-release
        with:
          install-only: 'true'

      - name: Check install!
        run: publish-release help

      - name: Check root directory
        run: |
          if [[ $(git diff --stat) != '' ]]; then
            echo 'should be clean'
            exit 1
          else
            exit 0
          fi
        shell: bash

  test_publish_release_action_custom_dir_root:
    if: ${{ needs.changes.outputs.pr == 'true' }}
    needs:
      - changes

    runs-on: ubuntu-latest

    permissions:
      contents: read

    name: Install Custom publish-release and test presence in path with custom root dir
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          persist-credentials: false

      - name: Install publish-release
        uses: ./publish-release
        with:
          install-only: 'true'
          install-dir: /usr/bin
          use-sudo: true

      - name: Check install!
        run: publish-release help

      - name: Check install dir!
        run: |
          [[ $(dirname "$(which publish-release)") == /usr/bin ]]
        shell: bash

      - name: Check root directory
        run: |
          [[ -z $(git diff --stat) ]]
        shell: bash

  test_publish_release_action_custom_dir:
    if: ${{ needs.changes.outputs.pr == 'true' }}
    needs:
      - changes

    strategy:
      matrix:
        os:
          - macos-latest
          - ubuntu-latest

    runs-on: ${{ matrix.os }}

    permissions:
      contents: read

    name: Install Custom path publish-release and test presence in path
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          persist-credentials: false

      - name: Install publish-release
        uses: ./publish-release
        with:
          install-only: 'true'
          install-dir: "$HOME/.prtest"

      - name: Check install!
        run: publish-release help

      - name: Check install dir!
        run: |
          [[ $(dirname "$(which publish-release)") == "$HOME/.prtest" ]]
        shell: bash

      - name: Check root directory
        run: |
          [[ -z $(git diff --stat) ]]
        shell: bash

  test_publish_release_action_wrong:
    if: ${{ needs.changes.outputs.pr == 'true' }}
    needs:
      - changes

    strategy:
      matrix:
        os:
          - macos-latest
          - ubuntu-latest

    runs-on: ${{ matrix.os }}

    permissions:
      contents: read

    name: Try to install a wrong publish-release
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          persist-credentials: false

      - name: Install publish-release
        uses: ./publish-release
        with:
          install-only: 'true'
          publish-release-version: 'honk'
        continue-on-error: true
